# Generated by Django 5.0.1 on 2024-01-22 12:39

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_advisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpage',
            name='advisors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='jobs.advisor'),
        ),
    ]
