# Generated by Django 4.2.9 on 2024-02-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobtagindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
