# Generated by Django 4.2.9 on 2024-01-24 20:47

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_banner_cta_homepage_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_subtitle',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
