# Generated by Django 4.2.9 on 2024-01-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_banner_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
