# Generated by Django 4.2.9 on 2024-02-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
