# Generated by Django 4.2.9 on 2024-02-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_footer_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
