# Generated by Django 5.0.12 on 2025-07-30 11:38

import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_homepage_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='extra',
            field=wagtail.fields.StreamField([('cards', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Add your title.', required=True)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(max_length=40, required=True)), ('text', wagtail.blocks.TextBlock(max_length=200, required=True)), ('button_page', wagtail.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.blocks.URLBlock(help_text='If the button_page is selected, that will be used first.', required=False))])))])), ('heading_block', wagtail.blocks.StructBlock([('heading_text', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('size', wagtail.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a heading size'), ('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))])), ('paragraph_block', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('image_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.blocks.CharBlock(required=False)), ('attribution', wagtail.blocks.CharBlock(required=False))])), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert a URL to embed. For example, https://www.youtube.com/watch?v=SGJFWirQ3ks', icon='media')), ('card', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'])), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))], group='Sections')), ('featured_posts', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=False)), ('posts', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(page_type=['blog.BlogPage', 'jobs.JobPage'])))], group='Sections')), ('team_member', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('name', wagtail.blocks.RichTextBlock(features=['H3', 'H4'], required=True)), ('text', wagtail.blocks.RichTextBlock(required=False)), ('telephone', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Choose Phone number link type--', required=False)), ('email', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Choose email link type--', required=False))], group='Sections')), ('member', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Add your title.', required=False)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('team_member', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('name', wagtail.blocks.RichTextBlock(features=['H3', 'H4'], required=True)), ('text', wagtail.blocks.RichTextBlock(required=False)), ('telephone', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Choose Phone number link type--', required=False)), ('email', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Choose email link type--', required=False))]))])))], group='Sections'))], blank=True, help_text='Use this section to make the website better!.'),
        ),
    ]
