# Generated by Django 4.2.9 on 2024-02-08 12:57

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_footertext_address_footertext_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footertext',
            name='address',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
