# Generated by Django 4.2.9 on 2024-02-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_footertext_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footertext',
            name='address',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='email',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='footer_image',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='phone',
        ),
    ]
