# Generated by Django 4.2.9 on 2024-02-08 13:37

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_footertext_address_remove_footertext_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='address',
            field=wagtail.fields.RichTextField(blank=True, help_text='Write your Address here...', null=True),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='phone',
            field=models.CharField(blank=True, help_text='Write your phone number here...', max_length=255, null=True, verbose_name='Your Phone Number'),
        ),
    ]
