# Generated by Django 4.2.9 on 2024-02-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_navigationsettings_address_navigationsettings_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsettings',
            name='address',
            field=models.CharField(blank=True, help_text='Write your Address here...', max_length=255, null=True),
        ),
    ]
