# Generated by Django 4.2.9 on 2024-02-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_navigationsettings_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='social_text',
            field=models.CharField(blank=True, help_text='Write the Follow us here...', max_length=255, null=True, verbose_name='Social Media Phrase'),
        ),
    ]
