# Generated by Django 4.2.9 on 2024-02-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_navigationsettings_social_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsettings',
            name='social_text',
            field=models.CharField(help_text='Write the Follow us here...', max_length=255, null=True, verbose_name='Social Media Phrase'),
        ),
    ]
