# Generated by Django 4.2.9 on 2024-02-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_navigationsettings_social_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='contact_phrase',
            field=models.CharField(blank=True, help_text='Write What you would like to say as Contact.. Ex. Contact Us, Contact, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='contact_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
