# Generated by Django 4.2.9 on 2024-02-09 11:00

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_navigationsettings_contact_phrase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsettings',
            name='contact_phrase',
            field=wagtail.fields.RichTextField(blank=True, help_text='Write What you would like to say as Contact..on the FOOTER. Example: Contact Us, Contact, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='contact_url',
            field=models.URLField(blank=True, help_text='For it to show, you must write a contact_phrase, if not, the url link does not show on the Footer, on top of Address...', null=True),
        ),
    ]
