# Generated by Django 4.2.9 on 2024-02-09 12:52

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_navigationsettings_contact_phrase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsettings',
            name='contact_url',
            field=wagtail.fields.RichTextField(blank=True, help_text='For it to show, you must write a contact_phrase, if not, the url link does not show on the Footer, on top of Address...', null=True),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='email',
            field=wagtail.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='phone',
            field=wagtail.fields.RichTextField(blank=True, help_text='Write your phone number here...', max_length=255, null=True, verbose_name='Your Phone Number'),
        ),
    ]
