# Generated by Django 4.2.9 on 2024-02-13 10:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('base', '0013_alter_navigationsettings_contact_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='header_cta',
            field=models.CharField(blank=True, help_text='Text to display on Call to Action on Header', max_length=255, verbose_name='Header CTA'),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='address',
            field=wagtail.fields.RichTextField(blank=True, help_text='Write your Address here...', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='contact_url',
            field=wagtail.fields.RichTextField(blank=True, help_text='Pick Link using / on the area. The url link will show on the Footer, on top of Address, below Contact_Phrase...', null=True),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='email',
            field=wagtail.fields.RichTextField(blank=True, help_text='Write your email here. Before, choose / and Link, then phone_link...', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='phone',
            field=wagtail.fields.RichTextField(blank=True, help_text='Write your phone number here. Before, choose / and Link, then email_link...', max_length=255, null=True, verbose_name='Your Phone Number'),
        ),
    ]
