# Generated by Django 4.2.9 on 2024-02-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_navigationsettings_header_cta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsettings',
            name='header_cta',
            field=models.CharField(blank=True, help_text='Text to display on Call to Action on Header', max_length=255, null=True, verbose_name='Header CTA'),
        ),
    ]
