# Generated by Django 5.1 on 2025-08-08 00:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_footertext_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='privacy_phrase',
            field=wagtail.fields.RichTextField(blank=True, help_text='Write What you would like to say as Privacy..on the FOOTER. Example: Privacy Policy, Policy, etc.', null=True),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='privacy_url',
            field=wagtail.fields.RichTextField(blank=True, help_text='Pick Link using / on the area. The url link will show on the Footer, below Contact_Phrase...', null=True),
        ),
    ]
