# Generated by Django 5.1 on 2025-08-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_navigationsettings_privacy_cta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationsettings',
            name='privacy_phrase',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='privacy_url',
        ),
    ]
