# Generated by Django 5.1 on 2025-08-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_navigationsettings_privacy_phrase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationsettings',
            name='privacy_cta',
        ),
    ]
